#!/bin/sh

# set -x

STATUS=$(which rlwrap > /dev/null)

if [ $? -ne 0 ]; then
    echo "Can't find rlwrap."
    exit 1
fi

if [ -z "$FORTH" ]; then
    FORTH=ficl
fi

if [ "$FORTH" = "ficl" ]; then
    if [ "$#" -eq 0 ]; then
        rlwrap -n ficl
    else
        rlwrap -n ficl  $*
    fi
    exit 0
fi

if [ "$FORTH" = "atlast" ]; then
    if [ -d "/usr/local/lib/Small" ]; then
        LD_LIBRARY_PATH=/usr/local/lib/Small
        export LD_LIBRARY_PATH
    fi
    rlwrap -n atlast $*
fi

if [ "$FORTH" = "gforth" ]; then
    gforth $*
fi
